import aboboradanta from '../assets/plants/aboboradanta.jpg';
import acafrao from '../assets/plants/acafrao.jpg';
import barbatimao from '../assets/plants/barbatimao.jpg';
import boldo from '../assets/plants/boldo.jpg';
import cafe from '../assets/plants/cafe.jpg';
import camomila from '../assets/plants/camomila.jpg';
import canademacaco from '../assets/plants/canademacaco.jpg';
import canela from '../assets/plants/canela.jpg';
import capimlimao from '../assets/plants/capimlimao.jpg';
import dentedeleao from '../assets/plants/dentedeleao.jpg';
import ervabaleeira from '../assets/plants/ervabaleeira.jpg';
import ervacidreira from '../assets/plants/ervacidreira.jpg';
import ervadebicho from '../assets/plants/ervadebicho.jpg';
import ervadebugre from '../assets/plants/ervadebugre.jpg';
import ervadoce from '../assets/plants/ervadoce.jpg';
import espinheirasanta from '../assets/plants/espinheirasanta.jpg';
import funcho from '../assets/plants/funcho.jpg';
import gengibre from '../assets/plants/gengibre.jpg';
import guaco from '../assets/plants/guaco.jpg';
import hortelapimenta from '../assets/plants/hortelapimenta.jpg';
import insulinavegetal from '../assets/plants/insulinavegetal.jpg';
import iperoxo from '../assets/plants/iperoxo.jpg';
import jabuticaba from '../assets/plants/jabuticaba.jpg';
import jatoba from '../assets/plants/jatoba.jpg';
import jurubeba from '../assets/plants/jurubeba.jpg';
import lagrimadenossasenhora from '../assets/plants/lagrimadenossasenhora.jpg';
import liriodobrejo from '../assets/plants/liriodobrejo.jpg';
import lobeira from '../assets/plants/lobeira.jpg';
import losna from '../assets/plants/losna.jpg';
import patadevaca from '../assets/plants/patadevaca.jpg';
import taioba from '../assets/plants/taioba.jpg';
import tiririca from '../assets/plants/tiririca.jpg';
import tomatecereja from '../assets/plants/tomatecereja.jpg';
import tomilho from '../assets/plants/tomilho.jpg';
import urtiga from '../assets/plants/urtiga.jpg';
import urucum from '../assets/plants/urucum.jpg';
import valeriana from '../assets/plants/valeriana.jpg';
import vassoura from '../assets/plants/vassoura.jpg';
import vique from '../assets/plants/vique.jpg';

export function getImage(name: string) {
  if (name === "Abóbora-D'Anta") return aboboradanta;
  if (name === "Açafrão") return acafrao;
  if (name === "Barbatimão") return barbatimao;
  if (name === "Boldo") return boldo;
  if (name === "Café") return cafe;
  if (name === "Camomila") return camomila;
  if (name === "Cana-De-Macaco") return canademacaco;
  if (name === "Canela") return canela;
  if (name === "Capim Limão") return capimlimao;
  if (name === "Dente-De-Leão") return dentedeleao;
  if (name === "Erva-Baleeira") return ervabaleeira;
  if (name === "Erva-Cidreira") return ervacidreira;
  if (name === "Erva-De-Bicho") return ervadebicho;
  if (name === "Erva-de-bugre") return ervadebugre;
  if (name === "Erva-doce") return ervadoce;
  if (name === "Espinheira-santa") return espinheirasanta;
  if (name === "Funcho") return funcho;
  if (name === "Gengibre") return gengibre;
  if (name === "Guaco") return guaco;
  if (name === "Hortelã-Pimenta") return hortelapimenta;
  if (name === "Insulina Vegetal") return insulinavegetal;
  if (name === "Ipê-roxo") return iperoxo;
  if (name === "Jabuticaba") return jabuticaba;
  if (name === "Jatobá") return jatoba;
  if (name === "Jurubeba") return jurubeba;
  if (name === "Lágrima de Nossa Senhora") return lagrimadenossasenhora;
  if (name === "Lírio do brejo") return liriodobrejo;
  if (name === "Lobeira") return lobeira;
  if (name === "Losna") return losna;
  if (name === "Pata-de-Vaca") return patadevaca;
  if (name === "Taioba") return taioba;
  if (name === "Tiririca") return tiririca;
  if (name === "Tomate-Cereja") return tomatecereja;
  if (name === "Tomilho") return tomilho;
  if (name === "Urtiga") return urtiga;
  if (name === "Urucum") return urucum;
  if (name === "Valeriana") return valeriana;
  if (name === "Vassoura") return vassoura;
  if (name === "Vique") return vique;
  return '';
}